# Generated by Django 4.1 on 2023-07-11 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userprofile_userbalanceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_coins', models.FloatField(default=0)),
                ('debit_coins', models.FloatField(default=0)),
                ('net_coins', models.FloatField(default=0)),
                ('game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_transaction_history',
            },
        ),
    ]
