# Generated by Django 4.2.2 on 2023-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usertransactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthtokens',
            name='access_token',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='userauthtokens',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
