# Generated by Django 4.2.3 on 2023-07-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusermaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmaster',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='superagentmaster',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
