# Generated by Django 4.2.3 on 2023-07-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusermaster', '0002_alter_agentmaster_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superagentmaster',
            name='current_limit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
