# Generated by Django 4.2.2 on 2023-07-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allusermaster', '0004_remove_agentmaster_super_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmaster',
            name='agent_master',
        ),
    ]
