# Generated by Django 4.2.2 on 2023-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusermaster', '0006_alter_agentmaster_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmaster',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='superagentmaster',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
