# Generated by Django 4.2.2 on 2023-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusermaster', '0007_agentmaster_password_clientmaster_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmaster',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='superagentmaster',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
